services:
  traefik:
    image: traefik:3.6.5
    ports:
      - 80:80
      # Port 443 is technically not needed for the tunnel, but good to keep if we ever switch back
      - 443:443
    restart: always
    labels:
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      - traefik.docker.network=traefik-public
      
      # Dashboard Configuration
      - traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080
      
      # HTTP Router (Tunnel terminates here, so we only need HTTP)
      - traefik.http.routers.traefik-dashboard-http.entrypoints=http
      - traefik.http.routers.traefik-dashboard-http.rule=Host(`traefik.${DOMAIN?Variable not set}`)
      - traefik.http.routers.traefik-dashboard-http.service=api@internal
      - traefik.http.routers.traefik-dashboard-http.middlewares=admin-auth

      # Auth Middleware
      - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      # Disable HTTPS/ACME entrypoints and resolvers since Cloudflare handles SSL
      - --accesslog
      - --accesslog.format=json
      - --log
      - --log.level=INFO
      - --log.format=json
      - --api
      - --api.insecure=false

    networks:
      - traefik-public

networks:
  traefik-public:
    external: true